// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginUpdateInfo = { name: string; currentVersion: string; latestVersion: string };

export type PluginUpdateNotification = { updateCount: number; plugins: Array<PluginUpdateInfo> };

export type UpdateInfo = {
  replyEventId: string;
  version: string;
  downloaded: boolean;
  /**
   * Whether the app can download and install this update itself. When false, the
   * user has to go download the new version (e.g. Linux .deb/.rpm installs).
   */
  installable: boolean;
};

export type UpdateResponse = { type: "ack" } | { type: "action"; action: UpdateResponseAction };

export type UpdateResponseAction = "install" | "skip";

export type YaakNotification = {
  timestamp: string;
  timeout: number | null;
  id: string;
  title: string | null;
  message: string;
  color: string | null;
  action: YaakNotificationAction | null;
};

export type YaakNotificationAction = { label: string; url: string };
