// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelPayload } from "./gen_models";

export type ProxyStartRequest = { port: number | null, };

export type ProxyStartResponse = { port: number, alreadyRunning: boolean, };

export type ProxyStopRequest = Record<string, never>;

export type RpcEventSchema = { model_write: ModelPayload, };

export type RpcSchema = { proxy_start: [ProxyStartRequest, ProxyStartResponse], proxy_stop: [ProxyStopRequest, boolean], };
