// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpExchange, ModelPayload } from "./gen_models";

export type ActionInvocation = { "scope": "global", action: GlobalAction, };

export type ActionMetadata = { label: string, defaultHotkey: string | null, };

export type GlobalAction = "proxy_start" | "proxy_stop";

export type ListActionsRequest = Record<string, never>;

export type ListActionsResponse = { actions: Array<[ActionInvocation, ActionMetadata]>, };

export type ListModelsRequest = Record<string, never>;

export type ListModelsResponse = { httpExchanges: Array<HttpExchange>, };

export type RpcEventSchema = { model_write: ModelPayload, };

export type RpcSchema = { execute_action: [ActionInvocation, boolean], list_actions: [ListActionsRequest, ListActionsResponse], list_models: [ListModelsRequest, ListModelsResponse], };
