[package]
name = "yaak-sse"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
ts-rs = { version = "10.0.0", features = ["serde-json-impl"] }
