[package]
name = "yaak-sse"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
ts-rs = { workspace = true, features = ["serde-json-impl"] }
