// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for an action group.
 *
 * Format: `namespace:group-name`
 * - Built-in: `yaak:export`
 * - Plugin: `plugin.my-plugin:utilities`
 */
export type ActionGroupId = string;
