// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionGroupId } from "./ActionGroupId";
import type { ActionScope } from "./ActionScope";

/**
 * Metadata about an action group.
 */
export type ActionGroupMetadata = { 
/**
 * Unique identifier for this group.
 */
id: ActionGroupId, 
/**
 * Display name for the group.
 */
name: string, 
/**
 * Optional description of the group's purpose.
 */
description: string | null, 
/**
 * Icon to display for the group.
 */
icon: string | null, 
/**
 * Sort order for displaying groups (lower = earlier).
 */
order: number, 
/**
 * Optional scope restriction (if set, group only appears in this scope).
 */
scope: ActionScope | null, };
