// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability status for an action.
 */
export type ActionAvailability = { "status": "available" } | { "status": "available-with-prompt", 
/**
 * Fields that will require prompting.
 */
prompt_fields: Array<string>, } | { "status": "unavailable", 
/**
 * Fields that are missing.
 */
missing_fields: Array<string>, } | { "status": "not-found" };
