// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an action group was registered from.
 */
export type ActionGroupSource = { "type": "builtin" } | { "type": "plugin", 
/**
 * Plugin reference ID.
 */
ref_id: string, 
/**
 * Plugin name.
 */
name: string, } | { "type": "dynamic", 
/**
 * Source identifier.
 */
source_id: string, };
