// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for an action.
 *
 * Format: `namespace:category:name`
 * - Built-in: `yaak:http-request:send`
 * - Plugin: `plugin.copy-curl:http-request:copy`
 */
export type ActionId = string;
