// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionGroupMetadata } from "./ActionGroupMetadata";
import type { ActionMetadata } from "./ActionMetadata";

/**
 * A group with its actions for UI rendering.
 */
export type ActionGroupWithActions = { 
/**
 * Group metadata.
 */
group: ActionGroupMetadata, 
/**
 * Actions in this group.
 */
actions: Array<ActionMetadata>, };
