// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters passed to action handlers.
 */
export type ActionParams = { 
/**
 * Arbitrary JSON parameters.
 */
data: unknown, };
