// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputPrompt } from "./InputPrompt";

/**
 * Result of action execution.
 */
export type ActionResult = { "type": "success", 
/**
 * Optional data to return.
 */
data: unknown, 
/**
 * Optional message to display.
 */
message: string | null, } | { "type": "requires-input", 
/**
 * Prompt to show user.
 */
prompt: InputPrompt, 
/**
 * Continuation token.
 */
continuation_id: string, } | { "type": "cancelled" };
