// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How strictly a context field is required.
 */
export type ContextRequirement = "not-required" | "optional" | "required" | "required-with-prompt";
