// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTarget } from "./ActionTarget";

/**
 * Current context state from the application.
 */
export type CurrentContext = { 
/**
 * Current workspace ID (if any).
 */
workspaceId: string | null, 
/**
 * Current environment ID (if any).
 */
environmentId: string | null, 
/**
 * Currently selected target (if any).
 */
target: ActionTarget | null, 
/**
 * Whether a window context is available.
 */
hasWindow: boolean, 
/**
 * Whether the context provider can prompt for missing fields.
 */
canPrompt: boolean, };
