// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextRequirement } from "./ContextRequirement";

/**
 * Specifies what context fields an action requires.
 */
export type RequiredContext = { 
/**
 * Action requires a workspace to be active.
 */
workspace: ContextRequirement, 
/**
 * Action requires an environment to be selected.
 */
environment: ContextRequirement, 
/**
 * Action requires a specific target entity (request, folder, etc.).
 */
target: ContextRequirement, 
/**
 * Action requires a window context (for UI operations).
 */
window: ContextRequirement, };
