// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An option in a select prompt.
 */
export type SelectOption = { label: string, value: string, };
