// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlight} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YOQOPOOQYOPOOOTOPOOObOQO'#CdOjOPO'#C`OuOSO'#CcQOOOOOQ]OPOOOzOQO,59OOOOO,59O,59OOOOO-E6b-E6bO!YOPO,58}OOOO1G.j1G.jO!bOSO'#CeO!gOPO1G.iOOOO,59P,59POOOO-E6c-E6c",
  stateData: "!u~OQQORPO~OZRO[TO~OTWOUXO~OZROYSX[SX~O]ZO~OU[OYWaZWa[Wa~O^]OYVa~O]_O~O^]OYVi~OQRTUT~",
  goto: "nYPPPPZPP^bhRVPTUPVQSPRYSQ^ZR`^",
  nodeNames: "⚠ url Protocol Host Path Placeholder PathSegment Query",
  maxTerm: 14,
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ".o~RgOs!jtv!jvw#Xw}!j}!O#r!O!P#r!P!Q%U!Q![%Z![!]'o!]!a!j!a!b+^!b!c!j!c!}+c!}#O#r#O#P!j#P#Q#r#Q#R!j#R#S#r#S#T!j#T#o+c#o;'S!j;'S;=`#R<%lO!jQ!oUUQOs!jt!P!j!Q!a!j!b;'S!j;'S;=`#R<%lO!jQ#UP;=`<%l!jR#`U^PUQOs!jt!P!j!Q!a!j!b;'S!j;'S;=`#R<%lO!jR#ycRPUQOs!jt}!j}!O#r!O!P#r!Q![#r![!]#r!]!a!j!b!c!j!c!}#r!}#O#r#O#P!j#P#Q#r#Q#R!j#R#S#r#S#T!j#T#o#r#o;'S!j;'S;=`#R<%lO!j~%ZOZ~V%de]SRPUQOs!jt}!j}!O#r!O!P#r!Q![%Z![!]#r!]!_!j!_!`&u!`!a!j!b!c!j!c!}%Z!}#O#r#O#P!j#P#Q#r#Q#R!j#R#S#r#S#T!j#T#o%Z#o;'S!j;'S;=`#R<%lO!jU&|Z]SUQOs!jt!P!j!Q![&u![!a!j!b!c!j!c!}&u!}#T!j#T#o&u#o;'S!j;'S;=`#R<%lO!jR'vcRPUQOs)Rt})R}!O)x!O!P)x!Q![)x![!]#r!]!a)R!b!c)R!c!})x!}#O)x#O#P)R#P#Q)x#Q#R)R#R#S)x#S#T)R#T#o)x#o;'S)R;'S;=`)r<%lO)RQ)YWTQUQOs)Rt!P)R!Q![)R![!]!j!]!a)R!b;'S)R;'S;=`)r<%lO)RQ)uP;=`<%l)RR*RcRPTQUQOs)Rt})R}!O)x!O!P)x!Q![)x![!]#r!]!a)R!b!c)R!c!})x!}#O)x#O#P)R#P#Q)x#Q#R)R#R#S)x#S#T)R#T#o)x#o;'S)R;'S;=`)r<%lO)R~+cO[~V+le]SRPUQOs!jt}!j}!O#r!O!P#r!Q![%Z![!],}!]!_!j!_!`&u!`!a!j!b!c!j!c!}+c!}#O#r#O#P!j#P#Q#r#Q#R!j#R#S#r#S#T!j#T#o+c#o;'S!j;'S;=`#R<%lO!jR-UdRPUQOs!jt}!j}!O#r!O!P#r!P!Q.d!Q![#r![!]#r!]!a!j!b!c!j!c!}#r!}#O#r#O#P!j#P#Q#r#Q#R!j#R#S#r#S#T!j#T#o#r#o;'S!j;'S;=`#R<%lO!jP.gP!P!Q.jP.oOQP",
  tokenizers: [0, 1, 2],
  topRules: {"url":[0,1]},
  tokenPrec: 77
})
