[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-upsert",
    "allow-delete",
    "allow-workspace-models",
    "allow-grpc-events",
    "allow-websocket-events",
]
