[package]
name = "yaak-crypto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aes-gcm = { version = "0.10.3", features = ["std"] }
base85 = "2.0.0"
keyring = { version = "4.0.0-alpha.1", features = ["vendored"] }
log = "0.4.26"
tauri = { workspace = true }
thiserror = "2.0.12"
tokio = { version = "1.43.0", default-features = false, features = ["macros", "test-util"] }
yaak-models = { workspace = true }
env_logger = "0.11.7"
