[package]
name = "yaak-crypto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
age = "0.11.1"
keyring = { version = "4.0.0-alpha.1", features = ["vendored"] }
tauri = { workspace = true }
yaak-models = { workspace = true }
thiserror = "2.0.12"
rand = "0.7.3"
tokio = "1.43.0"
async-trait = "0.1.87"
