// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strings intentionally retain unknown operators/types so they fail validation, rather than
 * disappearing during import or being treated as an empty, passing collection.
 */
export type HttpAssertion = { id: string, enabled: boolean, target: string, selector: string, operator: string, expected: string, expectedType: string, };

export type HttpAssertions = { version: number, checks: Array<HttpAssertion>, };
