// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AssertionReport = { definition: HttpAssertions, results: Array<AssertionResult>, error: string | null, };

export type AssertionResult = { assertionId: string, outcome: string, reason: string, actual: JsonValue | null, };

/**
 * Strings intentionally retain unknown operators/types so they fail validation, rather than
 * disappearing during import or being treated as an empty, passing collection.
 */
export type HttpAssertion = { id: string, enabled: boolean, target: string, selector: string, operator: string, expected: string, expectedType: string, };

export type HttpAssertions = { version: number, checks: Array<HttpAssertion>, };
