// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsonPathChild = {
/**
 * A single, escaped child accessor (e.g. .user, [0], or ["unusual.key"]).
 */
selector: string, label: string, kind: string, };

export type JsonPathChildren = { children: Array<JsonPathChild>,
/**
 * Discovery is sampled/bounded, never an assertion that other keys don't exist.
 */
truncated: boolean, };
