// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncModel } from "./gen_models";

export type GitCommit = { author: string, when: string, message: string | null, };

export type GitStatus = "added" | "conflict" | "current" | "modified" | "removed" | "renamed" | "type_change";

export type GitStatusEntry = { relaPath: string, status: GitStatus, staged: boolean, prev: SyncModel | null, next: SyncModel | null, };

export type GitStatusSummary = { path: string, headShorthand: string | null, headRef: string | null, entries: Array<GitStatusEntry>, };
