// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginSearchResponse = { results: Array<PluginVersion>, };

export type PluginVersion = { id: string, version: string, description: string | null, displayName: string | null, homepageUrl: string | null, repositoryUrl: string | null, checksum: string, readme: string | null, downloadUrl: string, yanked: boolean, };
